# Generated by Django 3.2.8 on 2021-10-05 18:29

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('profile_photo', cloudinary.models.CloudinaryField(default='image/upload/v1631717620/default_uomrne.jpg', max_length=255, verbose_name='image')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(default=datetime.datetime.now)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_storeadmin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
