# Generated by Django 3.2.8 on 2021-10-14 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211013_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='clerk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.users'),
        ),
    ]
