# Generated by Django 3.2.8 on 2021-10-11 06:36

import cloudinary.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('profile_photo', cloudinary.models.CloudinaryField(default='image/upload/v1631717620/default_uomrne.jpg', max_length=255, verbose_name='image')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_storeadmin', models.BooleanField(default=False)),
                ('store', models.CharField(max_length=50, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('number_of_items', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('store', models.CharField(default='A', max_length=50)),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.users')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('number_of_items', models.IntegerField(default=0)),
                ('buying_price', models.FloatField(default=0.0)),
                ('selling_price', models.FloatField(default=0.0)),
                ('store', models.CharField(default='A', max_length=50)),
                ('clerk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.users')),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('items_received', models.IntegerField(default=0)),
                ('items_spoiled', models.IntegerField(default=0)),
                ('date_delivered', models.DateTimeField(default=datetime.datetime.now)),
                ('store', models.CharField(default='A', max_length=50)),
                ('clerk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.users')),
            ],
        ),
    ]
