# Generated by Django 3.2.8 on 2021-10-09 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='clerk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.users'),
        ),
        migrations.AddField(
            model_name='item',
            name='clerk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.users'),
        ),
    ]
